### ISSUE TITLE
SVGs generated by term-transcript-cli don't show in Chrome when shown in their own tab

### ISSUE THREAD

**Issue by ilyagr** [slowli/term-transcript#49] opened 2023-04-01 04:49 UTC
I tried to generate some SVGs in https://github.com/martinvonz/jj/issues/1467. They are really nice!

While they show fine in the Github interface, if I navigate Chrome to an image's URL, e.g. https://user-images.githubusercontent.com/4123047/229266140-8344e2d8-5cdf-4612-965e-4a876528bbcb.svg, I get a black screen. Opening the dev console shows an error:

```
9265713-7e904105-56ee-4b41-a762-94b242adef7e.svg:67 
Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'none'".
Either the 'unsafe-inline' keyword, a hash ('sha256-3+MP7UGV/RwM1ZTSEYviydIfny9qgoZEjKe6HerBheQ='),
or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers,
style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present.
Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.
```

I'm not familiar enough with SVG or Chrome to understand it. Would it be possible to fix with some change to the SVG format, or is this a more fundamental problem?

**Update:** Firefox acts exactly the same as Chrome, and leaves a similar message in the console.

**Comment by slowli** [comment] 2023-04-03 14:02
Unfortunately, this problem cannot be fixed with changes to SVG; it is caused by [Content Security Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) (CSP) restrictions, which are configured on the HTTP server level. You may see the exact CSP config used by GitHub in the corresponding response header: `content-security-policy: default-src 'none'; script-src 'none'; img-src 'self'; media-src 'self'; sandbox;`, which essentially means that SVG cannot be styled with inline styles (that would require `style-src 'unsafe-inline'`, as suggested by the error message). As far as I understand, this CSP config does not allow *any* styling, even if we don't take into account that only inline styling makes sense for the generated snapshots (otherwise, a snapshot would not be self-contained).

Note that SVG files *committed* to a GitHub repo can be linked just fine. These files can be referenced using an URL like `https://github.com/$user/$repo/raw/HEAD/path/to/snapshot/snapshot.svg?sanitize=true`; e.g., this is how snapshots are linked to [the CLI readme](https://github.com/slowli/term-transcript/blob/master/cli/README.md):

```markdown
![Testing rainbow example][test-snapshot-link]

[test-snapshot-link]: https://github.com/slowli/term-transcript/raw/HEAD/cli/tests/snapshots/test.svg?sanitize=true
```

In this case, the CSP config is sane: `default-src 'none'; style-src 'unsafe-inline'; sandbox`.

**Comment by ilyagr** [comment] 2023-04-03 18:48
Thanks for the useful info and workarounds! It's unfortunate that SVG files are so restricted, but it is good to know.

**Comment by slowli** [comment] 2023-04-11 14:58
I've add the logic to the library & CLI app to render pure SVG in #53, but this still doesn't solve the issue. That is, inline styling restrictions in CSP concern not only HTML embedded into SVG, but SVG on its own as well. This is unfortunate; eliminating styles from SVG *entirely* could be theoretically possible, but it would result in bloated SVG, the template for which would be difficult to maintain.

As such, I feel that it's fair to close this issues with a "won't fix" resolution. If the website with your SVGs does not allow inline SVG styling, IMO it's the issue with overly restrictive CSP, not with SVGs.

**Closed by slowli** 2023-04-11 14:58 UTC
